### ISSUE TITLE
[Android Bootcamp] Week 3 Project: Twitter Client

### ISSUE THREAD

**Issue by amberved** [amberved/AVTweetsApp#1]
My app is complete, please review. /cc @codepathreview @codepath.

@nesquena 
I am hitting "Rate limit exceeded" issue. :(
Will try to re-record if it starts working again.

**Comment by nesquena** [comment]
@amberved Wait 15 minutes and it will come back. This is a well known issue https://dev.twitter.com/docs/rate-limiting/1.1

**Comment by amberved** [comment]
Updated the demo.
Thanks

**Comment by codepathreview** [comment]
:+1: nice work. A few notes after checking out the code:

* Good to see you were able to format the timestamp cleanly
* Nice to see you used the `SwipeRefreshLayout` for easy timeline refreshes
* Good to see you refreshed the timeline after composing a new tweet
*  Nice touch with the character count being displayed while the user composes a tweet
* Consider adding local persistence of tweets by using ActiveAndroid in the `Tweet` and `User`. See the [persistence guide](http://guides.codepath.com/android/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](http://guides.codepath.com/android/ActiveAndroid-Guide) for more details.

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.

**Comment by amberved** [comment]
@nesquena - I can use some help with the issue of not able to display data in ListView after I made changes for adding fragments. I do get data from twitter..
